default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password: mysql2342
  host: 127.0.0.1
  # port: 3307
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: reco_new_development

staging:
  <<: *default
  database: reco_new_staging

test:
  <<: *default
  database: reco_new_test
